name: ci

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
  push:
    branches:
      - master

env:
  PROJECT_ID: great-escape-294716
  IMAGE: ui-admin

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup GCP CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_DEPLOY_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure GCP docker registry
        run: |-
          gcloud --quiet auth configure-docker

      - name: Docker build
        run: |-
          docker build \
            --tag "$IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      - name: Docker tag default
        run: |-
          docker tag "$IMAGE:$GITHUB_SHA" \
            "eu.gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

      - name: Docker tag pull request image with PR number tags & Publish docker image
        if: ${{ github.event_name == 'pull_request' }}
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |-
          docker tag "$IMAGE:$GITHUB_SHA" \
            "eu.gcr.io/$PROJECT_ID/$IMAGE:pr-$PR_NUMBER-latest"
          docker tag "$IMAGE:$GITHUB_SHA" \
            "eu.gcr.io/$PROJECT_ID/$IMAGE:pr-$PR_NUMBER-$GITHUB_SHA"
          docker push "eu.gcr.io/$PROJECT_ID/$IMAGE:pr-$PR_NUMBER-latest"
          docker push "eu.gcr.io/$PROJECT_ID/$IMAGE:pr-$PR_NUMBER-$GITHUB_SHA"

      - name: Docker tag master image as latest & Publish docker image
        if: ${{ github.event_name == 'push' }}
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |-
          docker tag "$IMAGE:$GITHUB_SHA" \
            "eu.gcr.io/$PROJECT_ID/$IMAGE:latest"
          docker push "eu.gcr.io/$PROJECT_ID/$IMAGE:latest"

      - name: Install gcloud beta components
        run: |-
          gcloud components install beta --quiet

      - name: Trigger deployment GCP workflow
        run: |-
          gcloud beta workflows execute "${IMAGE}-delivery" --data "{ \"image\": \"$IMAGE\", \"tag\": \"$GITHUB_SHA\", \"service\": \"$IMAGE\"  }"
